let problems=[],pIndex=0,step=0,score=0,locked=false,lastSig='';
const app=document.getElementById('app'),bar=document.getElementById('bar'),progressText=document.getElementById('progressText'),scoreText=document.getElementById('scoreText');
const shuffle=a=>[...a].sort(()=>Math.random()-.5),pick=a=>a[Math.floor(Math.random()*a.length)];
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)}
const phrase=()=>`<div class="rule">毎回この言葉を読もう<br><strong>「内項の積＝外項の積の公式を利用して」</strong></div>`;
const ratioText=p=>`${p.a} ： ${p.b} ＝ ${p.c} ： ${p.d}`;
function makeBasic(pair){const[a,b]=pair,k=pick([2,3,4,5]);return{type:'basic',a,b,c:a*k,d:b*k}}
function makeBox(pos){const[a,b]=pick([[2,3],[3,4],[3,5],[4,5],[4,7],[5,6],[5,8],[6,7],[7,9]]),k=pick([2,3,4,5]),v=[a,b,a*k,b*k],answer=v[pos];v[pos]='□';return{type:'box',a:v[0],b:v[1],c:v[2],d:v[3],answer}}
function makePercent(item){const[kazuPct,hiroPct]=pick([[15,25],[20,30],[20,35],[25,40],[30,45],[30,50],[35,50],[40,60],[45,75]]);let story='';if(item==='wallet')story=`同じ入場料が、一成の財布の残高の${kazuPct}％、尋子の財布の残高の${hiroPct}％にあたります。財布の残高の比（一成：尋子）は？`;if(item==='bottle')story=`一成のペットボトルの残りの${kazuPct}％は、尋子のペットボトルの残りの${hiroPct}％と同じ量です。ペットボトルの残りの比（一成：尋子）は？`;if(item==='savings')story=`同じ金額が、一成の貯金の${kazuPct}％、尋子の貯金の${hiroPct}％にあたります。貯金額の比（一成：尋子）は？`;return{type:'percent',item,kazuPct,hiroPct,story}}
function generateProblems(){let sig='';do{const pairs=shuffle([[2,3],[3,4],[3,5],[4,5],[4,7],[5,6],[5,8],[6,7],[7,9]]).slice(0,3),basics=pairs.map(makeBasic),boxes=shuffle([0,1,2,3]).slice(0,3).map(makeBox),percents=[makePercent('wallet'),makePercent('bottle'),makePercent('savings')],changes=[makeChange('wallet'),makeChange('bottle'),makeChange('savings')];problems=[...basics,...boxes,...percents,...changes];sig=JSON.stringify(problems)}while(sig===lastSig);lastSig=sig}
const stepsFor=p=>p&&p.type==='change'?6:4,totalSteps=()=>problems.reduce((n,p)=>n+stepsFor(p),0);
function doneBefore(i){let n=0;for(let x=0;x<i;x++)n+=stepsFor(problems[x]);return n}
function updateHeader(){bar.style.width=`${Math.min(100,(doneBefore(pIndex)+step)/totalSteps()*100)}%`;progressText.textContent=`${Math.min(pIndex+1,12)} / 12 問`;scoreText.textContent=`正解 ${score}`}
function card(x){app.innerHTML=`<section class="card">${x}</section>`;updateHeader()}
function feedback(ok,msg){const f=document.getElementById('feedback');f.className='feedback '+(ok?'ok':'ng');f.innerHTML=msg}
function showNext(){document.getElementById('next').style.display='block'}
function choice(items){return shuffle(items).map(o=>`<button data-correct="${o.c?1:0}" onclick="answerChoice(this)">${o.t}</button>`).join('')}
function answerChoice(btn){if(locked)return;if(btn.dataset.correct==='1'){locked=true;score++;feedback(true,'正解！<br>もう一度声に出そう：<br><strong>「内項の積＝外項の積の公式を利用して」</strong>');document.querySelectorAll('.choices button').forEach(b=>b.disabled=true);showNext();updateHeader()}else{btn.disabled=true;feedback(false,'ちがいます。<br><strong>「内項の積＝外項の積の公式を利用して」</strong> と言いながら、もう一度考えよう。')}}
function nextStep(){step++;if(step>=stepsFor(problems[pIndex])){step=0;pIndex++}render()}
function render(){locked=false;if(pIndex>=problems.length)return finish();const p=problems[pIndex];if(p.type==='percent')return renderPercent(p);if(p.type==='change')return renderChange(p);if(step===0)return renderInner(p);if(step===1)return renderOuter(p);if(step===2)return renderEquation(p);return renderSolve(p)}
function renderInner(p){const c=`${p.b} × ${p.c}`;card(`<div class="tag">STEP 1 / 4</div>${phrase()}<div class="ratio">${ratioText(p)}</div><div class="hint">真ん中どうしが「内項」</div><div class="stepTitle">内項の積はどれ？</div><div class="choices">${choice([{t:c,c:1},{t:`${p.a} × ${p.d}`,c:0},{t:`${p.a} × ${p.c}`,c:0}])}</div><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次へ</button>`)}
function renderOuter(p){const c=`${p.a} × ${p.d}`;card(`<div class="tag">STEP 2 / 4</div>${phrase()}<div class="ratio">${ratioText(p)}</div><div class="hint">両はしが「外項」</div><div class="stepTitle">外項の積はどれ？</div><div class="choices">${choice([{t:c,c:1},{t:`${p.b} × ${p.c}`,c:0},{t:`${p.b} × ${p.d}`,c:0}])}</div><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次へ</button>`)}
function renderEquation(p){const c=`${p.b} × ${p.c} ＝ ${p.a} × ${p.d}`;card(`<div class="tag">STEP 3 / 4</div>${phrase()}<div class="ratio">${ratioText(p)}</div><div class="stepTitle">公式の形にしよう</div><div class="choices">${choice([{t:c,c:1},{t:`${p.a} × ${p.b} ＝ ${p.c} × ${p.d}`,c:0},{t:`${p.a} × ${p.c} ＝ ${p.b} × ${p.d}`,c:0}])}</div><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次へ</button>`)}
function renderSolve(p){if(p.type==='basic'){const l=p.b*p.c,r=p.a*p.d;card(`<div class="tag">STEP 4 / 4</div>${phrase()}<div class="ratio">${ratioText(p)}</div><div class="stepTitle">左右の積を計算しよう</div><div class="eqbox">${p.b} × ${p.c} ＝ ${p.a} × ${p.d}</div><div class="inputRow"><input id="l" inputmode="numeric" placeholder="内項"><b>＝</b><input id="r" inputmode="numeric" placeholder="外項"></div><button class="primary" style="width:100%;margin-top:14px" onclick="checkProducts(${l},${r})">答え合わせ</button><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次の問題へ</button>`)}else{card(`<div class="tag">STEP 4 / 4</div>${phrase()}<div class="ratio">${ratioText(p)}</div><div class="stepTitle">□の値を求めよう</div><div class="eqbox">${p.b} × ${p.c} ＝ ${p.a} × ${p.d}</div><div class="inputRow"><b>□ ＝</b><input id="x" inputmode="numeric"></div><button class="primary" style="width:100%;margin-top:14px" onclick="checkX(${p.answer})">答え合わせ</button><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次の問題へ</button>`)}}
function checkProducts(l,r){if(+document.getElementById('l').value===l&&+document.getElementById('r').value===r){locked=true;score++;feedback(true,`正解！ ${l} ＝ ${r}`);showNext();updateHeader()}else feedback(false,'もう一度計算しよう。')}
function checkX(a){if(+document.getElementById('x').value===a){locked=true;score++;feedback(true,`正解！ □ ＝ ${a}`);showNext();updateHeader()}else feedback(false,'内項の積＝外項の積になるようにもう一度。')}
function renderPercent(p){const a=p.kazuPct,b=p.hiroPct,g=gcd(a,b),sa=b/g,sb=a/g;if(step===0){const c=`一成 × ${a}％ ＝ 尋子 × ${b}％`;return card(`<div class="tag">文章題 STEP 1 / 4</div>${phrase()}<div class="story">${p.story}</div><div class="stepTitle">同じ量を式にしよう</div><div class="choices">${choice([{t:c,c:1},{t:`一成 × ${b}％ ＝ 尋子 × ${a}％`,c:0},{t:`一成 ＋ ${a}％ ＝ 尋子 ＋ ${b}％`,c:0}])}</div><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次へ</button>`)}if(step===1){const c=`一成 ： 尋子 ＝ ${b} ： ${a}`;return card(`<div class="tag">文章題 STEP 2 / 4</div>${phrase()}<div class="story">${p.story}</div><div class="eqbox">一成 × ${a}％ ＝ 尋子 × ${b}％</div><div class="stepTitle">比の形に直そう</div><div class="choices">${choice([{t:c,c:1},{t:`一成 ： 尋子 ＝ ${a} ： ${b}`,c:0},{t:`一成 ： 尋子 ＝ ${a+b} ： 100`,c:0}])}</div><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次へ</button>`)}if(step===2){const c=`${b} ： ${a}`;return card(`<div class="tag">文章題 STEP 3 / 4</div>${phrase()}<div class="story">${p.story}</div><div class="stepTitle">約分する前の比は？</div><div class="choices">${choice([{t:c,c:1},{t:`${a} ： ${b}`,c:0},{t:`${a/g} ： ${b/g}`,c:0}])}</div><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次へ</button>`)}card(`<div class="tag">文章題 STEP 4 / 4</div>${phrase()}<div class="story">${p.story}</div><div class="stepTitle">最も簡単な整数比にしよう</div><div class="eqbox">${b} ： ${a} → ？ ： ？</div><div class="inputRow"><input id="pa" inputmode="numeric" placeholder="一成"><b>：</b><input id="pb" inputmode="numeric" placeholder="尋子"></div><button class="primary" style="width:100%;margin-top:14px" onclick="checkPair(${sa},${sb})">答え合わせ</button><div id="feedback" class="feedback"></div><button id="next" class="next primary" onclick="nextStep()">次の問題へ</button>`)}
function checkPair(a,b){if(+document.getElementById('pa').value===a&&+document.getElementById('pb').value===b){locked=true;score++;feedback(true,`正解！ 一成：尋子 ＝ <strong>${a}：${b}</strong>`);showNext();updateHeader()}else feedback(false,'％の数字を反対側に置いて、最後に約分しよう。')}
function finish(){bar.style.width='100%';app.innerHTML=`<section class="card finish"><h2>ドリル完了！</h2><div class="rule">最後に3回読もう<br><strong>「内項の積＝外項の積の公式を利用して」</strong></div><p style="font-size:20px;font-weight:800">正解数：${score} / ${totalSteps()}</p><p class="note">「数字を変えてもう一度やる」で、新しい数字の12問を作ります。</p><button class="primary" style="width:100%" onclick="restart()">数字を変えてもう一度やる</button></section>`}
function restart(){generateProblems();pIndex=0;step=0;score=0;locked=false;render();scrollTo({top:0,behavior:'smooth'})}
window.addEventListener('DOMContentLoaded',()=>{generateProblems();render()});
